(function(){"use strict";
  const {PRESETS,slugify,fitRect,outputPath,zipStore}=MarketPackCore,MAX_FREE=3;let files=[];
  const $=id=>document.getElementById(id),fileInput=$("files"),drop=$("dropzone"),queue=$("queue"),pack=$("pack"),status=$("status");
  function markets(){return[...document.querySelectorAll('[name="market"]:checked')].map(x=>x.value)}
  function update(){
    queue.replaceChildren(...files.map((file,index)=>{const row=document.createElement("div");row.className="queue-item";const img=document.createElement("img");img.src=URL.createObjectURL(file);img.onload=()=>URL.revokeObjectURL(img.src);const text=document.createElement("div"),name=document.createElement("b"),meta=document.createElement("small");name.textContent=file.name;meta.textContent=`${(file.size/1048576).toFixed(1)} MB`;text.append(name,meta);const remove=document.createElement("button");remove.className="remove";remove.type="button";remove.setAttribute("aria-label",`Remove ${file.name}`);remove.textContent="×";remove.onclick=()=>{files.splice(index,1);update()};row.append(img,text,remove);return row}));
    pack.disabled=!files.length||!markets().length;status.textContent=files.length?`${files.length} source image${files.length===1?"":"s"} → ${files.length*markets().length} JPG files`:"Choose at least one image and marketplace.";
  }
  function add(list){const valid=[...list].filter(f=>["image/jpeg","image/png","image/webp"].includes(f.type)),room=MAX_FREE-files.length;files.push(...valid.slice(0,room));update();if(valid.length>room)status.textContent=`Free demo limit: added ${Math.max(room,0)} of ${valid.length}. Up to ${MAX_FREE} source images.`}
  $("browse").onclick=()=>fileInput.click();drop.onclick=e=>{if(e.target.id!=="browse")fileInput.click()};drop.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();fileInput.click()}};fileInput.onchange=()=>{add(fileInput.files);fileInput.value=""};
  for(const event of ["dragenter","dragover"]){drop.addEventListener(event,e=>{e.preventDefault();drop.classList.add("over")})}for(const event of ["dragleave","drop"]){drop.addEventListener(event,e=>{e.preventDefault();drop.classList.remove("over")})}drop.addEventListener("drop",e=>add(e.dataTransfer.files));
  $("quality").oninput=e=>$("quality-value").textContent=`${e.target.value}%`;document.querySelectorAll('[name="market"]').forEach(x=>x.onchange=update);
  function loadImage(file){return typeof createImageBitmap==="function"?createImageBitmap(file):new Promise((resolve,reject)=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error(`Could not decode ${file.name}`))};image.src=url})}
  function canvasBlob(canvas,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Image export failed")),"image/jpeg",quality))}
  pack.onclick=async()=>{
    if(pack.disabled)return;pack.disabled=true;const entries=[],selected=markets(),quality=Number($("quality").value)/100,mode=$("mode").value,userBackground=$("background").value;
    try{for(let i=0;i<files.length;i++){status.textContent=`Processing ${i+1} of ${files.length}…`;const image=await loadImage(files[i]);for(const key of selected){const preset=PRESETS[key],canvas=document.createElement("canvas");canvas.width=preset.width;canvas.height=preset.height;const ctx=canvas.getContext("2d",{alpha:false});ctx.fillStyle=preset.background==="user"?userBackground:preset.background;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";const rect=fitRect(image.width,image.height,canvas.width,canvas.height,mode);ctx.drawImage(image,rect.x,rect.y,rect.width,rect.height);const blob=await canvasBlob(canvas,quality);entries.push({name:outputPath($("product").value,i,preset),data:new Uint8Array(await blob.arrayBuffer())})}if(image.close)image.close()}
      status.textContent="Building ZIP…";const zip=zipStore(entries),url=URL.createObjectURL(new Blob([zip],{type:"application/zip"})),a=document.createElement("a");a.href=url;a.download=`marketpack-${slugify($("product").value)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent=`Done: ${entries.length} JPG files organized in one ZIP.`;
    }catch(error){status.textContent=`Could not create pack: ${error.message}`}finally{pack.disabled=false}
  };update();
})();
